executable = test.sh
request_cpus = 64
request_memory = 500000
request_gpus = 8
request_disk = 200G
requirements = (TARGET.CUDACapability >= 7.0) && (TARGET.CUDAGlobalMemoryMb >=80000)
log_root = /home/fli/llm_train/jobs/$(ClusterId)
error = $(log_root).err
output = $(log_root).out
log = $(log_root).log
MaxTime = 86400

periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))
queue
